import { describe, it, expect, vi, beforeEach } from 'vitest'
import { ExportService } from '../export'

// Mock external dependencies
vi.mock('xlsx', () => ({
  utils: {
    book_new: vi.fn(() => ({})),
    aoa_to_sheet: vi.fn(() => ({ '!cols': [] })),
    book_append_sheet: vi.fn(),
  },
  writeFile: vi.fn(),
}))

vi.mock('jspdf', () => {
  const mockDoc = {
    setFontSize: vi.fn(),
    setFont: vi.fn(),
    text: vi.fn(),
    splitTextToSize: vi.fn(() => ['line1', 'line2']),
    save: vi.fn(),
    internal: {
      pageSize: {
        height: 297,
      },
    },
  }
  return {
    default: vi.fn(() => mockDoc),
  }
})

vi.mock('jspdf-autotable', () => ({
  default: vi.fn(),
}))

vi.mock('html2canvas', () => ({
  default: vi.fn(() => Promise.resolve({
    toDataURL: vi.fn(() => 'data:image/png;base64,mock'),
    height: 100,
    width: 100,
  })),
}))

// Mock DOM methods
Object.defineProperty(window, 'URL', {
  value: {
    createObjectURL: vi.fn(() => 'mock-url'),
    revokeObjectURL: vi.fn(),
  },
})

describe('ExportService', () => {
  const mockData = [
    { id: 1, name: 'John Doe', email: 'john@example.com', active: true, joinDate: new Date('2023-01-01') },
    { id: 2, name: 'Jane Smith', email: 'jane@example.com', active: false, joinDate: new Date('2023-02-01') },
  ]

  const mockColumns = [
    { key: 'id', header: 'ID' },
    { key: 'name', header: 'Name' },
    { key: 'email', header: 'Email' },
    { key: 'active', header: 'Active', formatter: (value: boolean) => value ? 'Yes' : 'No' },
    { key: 'joinDate', header: 'Join Date' },
  ]

  beforeEach(() => {
    vi.clearAllMocks()
    
    // Mock document.createElement and appendChild
    const mockLink = {
      href: '',
      download: '',
      click: vi.fn(),
    }
    
    vi.spyOn(document, 'createElement').mockReturnValue(mockLink as any)
    vi.spyOn(document.body, 'appendChild').mockImplementation(() => mockLink as any)
    vi.spyOn(document.body, 'removeChild').mockImplementation(() => mockLink as any)
  })

  describe('exportToCSV', () => {
    it('should export data to CSV format', () => {
      ExportService.exportToCSV(mockData, mockColumns, {
        filename: 'test-export',
        includeTimestamp: false,
      })

      expect(document.createElement).toHaveBeenCalledWith('a')
      expect(document.body.appendChild).toHaveBeenCalled()
      expect(document.body.removeChild).toHaveBeenCalled()
    })

    it('should handle empty data', () => {
      expect(() => {
        ExportService.exportToCSV([], mockColumns)
      }).not.toThrow()
    })

    it('should apply custom formatters', () => {
      const columnsWithFormatter = [
        { key: 'active', header: 'Status', formatter: (value: boolean) => value ? 'Active' : 'Inactive' }
      ]

      expect(() => {
        ExportService.exportToCSV(mockData, columnsWithFormatter)
      }).not.toThrow()
    })

    it('should escape CSV special characters', () => {
      const dataWithSpecialChars = [
        { text: 'Hello, "World"' },
        { text: 'Line\nBreak' },
      ]
      const columns = [{ key: 'text', header: 'Text' }]

      expect(() => {
        ExportService.exportToCSV(dataWithSpecialChars, columns)
      }).not.toThrow()
    })
  })

  describe('exportToExcel', () => {
    it('should export data to Excel format', async () => {
      const XLSX = await import('xlsx')
      
      ExportService.exportToExcel(mockData, mockColumns, {
        filename: 'test-export',
        title: 'Test Report',
      })

      expect(XLSX.utils.book_new).toHaveBeenCalled()
      expect(XLSX.utils.aoa_to_sheet).toHaveBeenCalled()
      expect(XLSX.utils.book_append_sheet).toHaveBeenCalled()
      expect(XLSX.writeFile).toHaveBeenCalled()
    })

    it('should handle column widths', async () => {
      const columnsWithWidth = mockColumns.map(col => ({ ...col, width: 20 }))
      
      expect(() => {
        ExportService.exportToExcel(mockData, columnsWithWidth)
      }).not.toThrow()
    })
  })

  describe('exportToPDF', () => {
    it('should export data to PDF format', async () => {
      const jsPDF = await import('jspdf')
      const autoTable = await import('jspdf-autotable')
      
      ExportService.exportToPDF(mockData, mockColumns, {
        filename: 'test-export',
        title: 'Test Report',
        subtitle: 'Generated Report',
      })

      expect(jsPDF.default).toHaveBeenCalled()
      expect(autoTable.default).toHaveBeenCalled()
    })

    it('should handle custom metadata', () => {
      expect(() => {
        ExportService.exportToPDF(mockData, mockColumns, {
          customMetadata: {
            'Generated By': 'Test User',
            'Department': 'IT',
          },
        })
      }).not.toThrow()
    })
  })

  describe('exportElementToPDF', () => {
    it('should export HTML element to PDF', async () => {
      const mockElement = document.createElement('div')
      mockElement.innerHTML = '<h1>Test Content</h1>'

      await expect(
        ExportService.exportElementToPDF(mockElement, {
          filename: 'element-export',
        })
      ).resolves.not.toThrow()
    })

    it('should handle html2canvas errors', async () => {
      const html2canvas = await import('html2canvas')
      vi.mocked(html2canvas.default).mockRejectedValueOnce(new Error('Canvas error'))

      const mockElement = document.createElement('div')

      await expect(
        ExportService.exportElementToPDF(mockElement)
      ).rejects.toThrow('Failed to export to PDF')
    })
  })

  describe('generateReport', () => {
    it('should generate comprehensive report', async () => {
      const reportConfig = {
        title: 'Test Report',
        description: 'This is a test report',
        dateRange: {
          startDate: new Date('2023-01-01'),
          endDate: new Date('2023-12-31'),
          field: 'joinDate',
        },
        filters: {
          active: true,
          department: 'IT',
        },
        customSections: [
          {
            title: 'Summary',
            type: 'text' as const,
            data: 'This is a summary section',
          },
          {
            title: 'Data Table',
            type: 'table' as const,
            data: [['Name', 'Email'], ['John', 'john@example.com']],
            config: {
              headers: ['Name', 'Email'],
            },
          },
          {
            title: 'Metrics',
            type: 'metrics' as const,
            data: {
              'Total Users': 100,
              'Active Users': 85,
            },
          },
        ],
      }

      await expect(
        ExportService.generateReport(reportConfig, mockData, {
          filename: 'comprehensive-report',
        })
      ).resolves.not.toThrow()
    })

    it('should handle empty sections', async () => {
      const reportConfig = {
        title: 'Empty Report',
        customSections: [],
      }

      await expect(
        ExportService.generateReport(reportConfig, mockData)
      ).resolves.not.toThrow()
    })
  })

  describe('Helper methods', () => {
    it('should format values correctly', () => {
      // Test private method through public interface
      const testData = [
        { value: null },
        { value: undefined },
        { value: true },
        { value: false },
        { value: new Date('2023-01-01') },
        { value: 12345 },
        { value: 'string' },
      ]

      const columns = [{ key: 'value', header: 'Value' }]

      expect(() => {
        ExportService.exportToCSV(testData, columns)
      }).not.toThrow()
    })

    it('should handle nested object values', () => {
      const nestedData = [
        { user: { profile: { name: 'John Doe' } } },
        { user: { profile: { name: 'Jane Smith' } } },
      ]

      const columns = [{ key: 'user.profile.name', header: 'Name' }]

      expect(() => {
        ExportService.exportToCSV(nestedData, columns)
      }).not.toThrow()
    })
  })
})